parameters:
    project_url: https://github.com/schulit/openlibrary

common:
    app:
        url: "%env(APP_URL)%"
        name: "%env(APP_NAME)%"
        version: "%version%"
        project_url: "%project_url%"
        logo: "%env(APP_LOGO)%"
        small_logo: "%env(APP_SMALLLOGO)%"
        logo_link: 'dashboard'
    autoconfig:
        entity_id: '%env(SAML_ENTITY_ID)%'
        app_name: "%env(APP_NAME)%"
        app_icon: 'fas fa-book-open'
        saml_cert_file: '%sp_cert_file%'
        role_hierarchy: '%security.role_hierarchy.roles%'

services:
    SchulIT\CommonBundle\Monolog\DatabaseHandler:
        autoconfigure: true
        autowire: true
        arguments:
            $connection: '@doctrine.dbal.logger_connection'
