framework:
    rate_limiter:
        mail:
            policy: "fixed_window"
            limit: "%env(int:MAILER_LIMIT)%"
            interval: "%env(MAILER_INTERVAL)%"

    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: "%env(MESSENGER_TRANSPORT_DSN)%?queue_name=async"
            mail:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%?queue_name=mail"
                rate_limiter: mail

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: mail
